package com.tts.springbootbasics;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.CreationTimestamp;

// Creates POJO - usable by JPA services
@Entity
public class Customer
{
    // Id allows id as primary key; GeneratedValue allows id to be generated by
    // database
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String firstName;
    private String lastName;
    private String address;
    private String city;
    private String state;
    private Integer zip;
    private Integer phoneNumber;
    private String email;

    // Column matches attribute name with database column name; CreationTimestamp
    // sets time/date of creation
    @Column
    @CreationTimestamp
    private Date signedUp;

    // No args Constructor
    public Customer()
    {

    }

    // Full tilt Constructor
    public Customer(String firstName, String lastName, String address, String city, String state, Integer zip, Integer phoneNumber, String email, Date signedUp)
    {
        super();
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.signedUp = signedUp;
    }

    public String getFirstName()
    {
        return firstName;
    }

    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    public String getLastName()
    {
        return lastName;
    }

    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    public String getAddress()
    {
        return address;
    }

    public void setAddress(String address)
    {
        this.address = address;
    }

    public String getCity()
    {
        return city;
    }

    public void setCity(String city)
    {
        this.city = city;
    }

    public String getState()
    {
        return state;
    }

    public void setState(String state)
    {
        this.state = state;
    }

    public Integer getZip()
    {
        return zip;
    }

    public void setZip(Integer zip)
    {
        this.zip = zip;
    }

    public Integer getPhoneNumber()
    {
        return phoneNumber;
    }

    public void setPhoneNumber(Integer phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public Date getSignedUp()
    {
        return signedUp;
    }

    public void setSignedUp(Date signedUp)
    {
        this.signedUp = signedUp;
    }

    @Override
    public String toString()
    {
        return "Customer [firstName=" + firstName + ", lastName=" + lastName + ", address=" + address + ", city=" + city + ", state=" + state + ", zip=" + zip + ", phoneNumber=" + phoneNumber
                + ", email=" + email + ", signedUp=" + signedUp + "]";
    }

}
